title: Preston Robertson # your name (or website title) here
logo: "/images/Picture of Me Senior Year.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Portfolio of notable data science and machine learning engineering related projects.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/preston-robertson-5b653222b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
